### ISSUE TITLE
Separate class files

### ISSUE THREAD

**Issue by hamidnazari** [Innablr/cloudformation-seed#11]
Now that we're dealing a proper pip package, let's break down the `deploy_stack.py` file into multiple class files to increase readability and maintainability.

Also, shouldn't the `examples` directory be in the root of the repo instead of `deploy_stack` directory with is the src for the package?

**Comment by omarst9** [comment]
Raised PR #22 to address these enhancements

**Comment by omarst9** [comment]
PR merged to develop
