### ISSUE TITLE
type error handling bug

### ISSUE THREAD

**Issue by hamidnazari** [Innablr/cloudformation-seed#34]
if an invalid resource type is entered, i.e. anything but `stackset` or `stack`, reportedly cf-seed does not throw any errors or warnings and just skips the stack, resulting in unexpected behaviours or other errors down the track that are not directly causing the problem.

cf-seed should verify that a parameter file is valid before executing it.

**Comment by abukharov** [comment]
I don't want to strictly validate the configuration against the schema to allow people to use it in different unexpected ways. For example this is how the pattern with YAML anchors came around. Some people may want to combine cf-seed configuration with something else, or postprocess/preprocess it.

I think a strict validation will greatly limit the potential of the tool
